# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_API:         ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        auth_token_user_provider:
            id: auth_token_user_provider

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js|utils)/
            security: false
            stateless: true
            anonymous: true
        public:
      # since anonymous is allowed users will not be forced to login
            pattern:  login|register
            anonymous: true
            security: false
            stateless: true

        main:
            pattern: ^/
            stateless: true
            simple_preauth:
                authenticator: auth_token_authenticator
            provider: auth_token_user_provider
            anonymous: ~

    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt
            cost: 12