vehicule_index:
    path:     /
    defaults: { _controller: "AppBundle:Vehicule:index" }
    methods:  GET

vehicule_create:
    path:     /create
    defaults: { _controller: "AppBundle:Vehicule:createVehicule" }
    methods:  [GET, POST]

vehicule_update:
    path:     /{id}/update
    defaults: { _controller: "AppBundle:Vehicule:updateVehicule" }
    methods:  [GET, POST]

vehicule_delete:
    path:     /vehicule/{id}/delete
    defaults: { _controller: "AppBundle:Vehicule:deleteVehicule" }
    methods:  DELETE
