app_reparation:
    resource: "@AppBundle/Resources/config/routing/reparation.yml"   
    prefix: /

app_vehicule:
    resource: "@AppBundle/Resources/config/routing/vehicule.yml"   
    prefix: /vehicule

app_utils:
    resource: "@AppBundle/Resources/config/routing/utils.yml"   
    prefix: /utils

app_user:
    resource: "@AppBundle/Resources/config/routing/user.yml"  
    prefix: /user
    
auth-tokens:
    path:      /login
    defaults: { _controller: "AppBundle:AuthToken:postAuthTokens" }
    methods:  [POST,OPTIONS,GET]

auth-tokens_delete:
    path:      /token/delete
    defaults: { _controller: "AppBundle:AuthToken:removeAuthTokens" }